<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lb_osm"
 *
 * Auto generated by Extension Builder 2016-09-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'OSM_Karte',
	'description' => 'Mit dieser Extension lässt sich eine interaktive Karte anlegen. Als Tools werden Leaflet und OSM oder Google Maps eingesetzt.',
	'category' => 'plugin',
	'author' => 'Leonhard Bolschakow',
	'author_email' => 'leonhard@bolschakow.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);


